name: Create Archive
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: 'figurasoundpack.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'
    - uses: actions/upload-artifact@v3.0.0
    - name: Upload Archive
      with:
        path: "figurasoundpack.zip"
